### ISSUE TITLE
instagram scraping issue

### ISSUE THREAD

**Issue by thraxil** [thraxil/spokehub#231]
for the last few hours, instagram hashtag scraping has been failing. Looks like a missing caption field on one of the items:

```
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/spokehub/spokehub/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/www/spokehub/spokehub/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/spokehub/spokehub/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/spokehub/spokehub/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/var/www/spokehub/spokehub/spokehub/main/management/commands/update_now.py", line 40, in handle
    instagram_hashtag_scrape()
  File "/var/www/spokehub/spokehub/spokehub/instagram/__init__.py", line 149, in hashtag_scrape
    e = Entry(entry)
  File "/var/www/spokehub/spokehub/spokehub/instagram/scrape.py", line 45, in __init__
    self.caption = d['caption']
KeyError: 'caption'
```

fixing it should just be a matter of adding an empty string default caption.

**Comment by thraxil** [comment]
fixed.
